### ISSUE TITLE
Add a discussion on robust methods in Chapter 2

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/TTS#1]
Rob could you please add a very simple intro on the issue? I added a small simulation to illustrate the impact of outliers on the estimation of the ACF. Maybe we could present Yanyuan's estimator (without defining it) and show that it works. It could be good to add an example with real data, I think the example with high-frequency financial data would be perfect. Merci bcp!

**Comment by robertomolinari** [comment]
Yanyuan’s estimator is not implemented in R. I used the “robber” package. Where can I find the high-frequency financial data?

**Comment by stephaneguerrier** [comment]
Hi Rob, that's perfect. Code for the high-freq data is in section 1.2:

``` r
# Load packages
library(timeDate)

# Load "high-frequency" Starbucks returns for Jul 01 2011
data(sbux.xts, package = "highfrequency")

# Plot returns
par(mfrow = c(1,2))
plot(sbux.xts[1:89], main = " ", ylab = "Returns")
plot(sbux.xts, main = " ", ylab = "Returns")
```

**Comment by stephaneguerrier** [comment]
@robertomolinari this is done, right?

**Comment by coatless** [comment]
@stephaneguerrier missing the code for the simulation.

The robust comments were included in: 8d4476cc047199b4b3da6d835303bcc8e358c153

along with spelling tweaks.

**Comment by stephaneguerrier** [comment]
Ok, thanks. Please close this issue when u get the code.

**Comment by robertomolinari** [comment]
Done !
