### ISSUE TITLE
Review Chap 1

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/TTS#13]
Hi guys, James, Rob and I reviewed chapter 1. If you have a moment, could you go through it and let me know if you have any comments or suggestions? Thanks!

**Comment by samorso** [comment]
Done! This is great. Found two minor typos, but don't how I can correct it. Since it is an Intro chapter, my only suggestion would be to add more real data examples, there ain't any for AR(1) and MA(1) for example.

**Comment by HaotianXu** [comment]
Done! 
1. Would it be better to write the definition of all the information avaiable up to time  t−1 as \Omega_t = \sigma\left(X_{t-1}, X_{t-2}, ..., X_0 \right)?
1. In part "1.3.1 White noise processes", both the \sigma^2 and the \sigma^2_{\omega} are used.

**Comment by coatless** [comment]
@samorso Quick edits can be done with: http://tts.smac-group.com/index.html#contributing

For longer edits, see: https://github.com/SMAC-Group/TTS/blob/master/README.md

@HaotianXu: Where is  \sigma^2_{\omega}?

http://tts.smac-group.com/introduction.html#white-noise-processes

I see:

https://github.com/SMAC-Group/TTS/commit/150d4e724c5eb48755705b3b1e91a2c5cb6ade78#diff-547c34c529c929ed3009c085b95fa811R148

**Comment by stephaneguerrier** [comment]
@samorso and @HaotianXu Merci bcp!

**Comment by stephaneguerrier** [comment]
@moufle7 thanks for the suggestions. I included them in the text!
