### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/TTS#28]
James could you please address the following problems:
- [x] Spell check chapter 3!
- [x] Theorem 3.1 is off
- [x] Ref "@shumway2011time" below theorem 3.1 does not work.
- [x] Several references in section 3.3.1.1 do not work
- [x] Add a caption to AR(2) graph and reference in text (see Example 3.7)
- [x] Several reference in section 3.3.1.2 do not work.
- [x] Add caption to figure in example 3.9 and make link in text.
- [ ] Add Model index in the second figure on example 3.9

**Comment by coatless** [comment]
Cleaned up a majority of formatting issues. Graph issues remain.

When 3.1 was checked in, example numbers shifted.... I'm assuming: 
1. Autocorrelation AR(2) Processes is Example 3.7 which has points on the graph? So the legend is the model?
2. Model index (e.g. name) is what we talked about for `exts` on thursday. Legends are nasty for anything done with `grid.arrange()` might need to just have a label...
