### ISSUE TITLE
Add proof of Theorem for Chapter 2 in Appendix

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/TTS#3]
@HaotianXu : could you please add the proof of the theorem in chapter 2, i.e.

**Theorem:** If $X_t$ is white noise with finite fourth moment, then $\hat{\rho}(h)$ is approximately normally distributed with mean $0$ and variance $n^{-1}$ for all fixed $h$.

The proof is on pages 16 and 17 of "Time series notes (part 1)". This proof is very informal and can certainly be greatly improved. Please feel free to modify it. Thanks!

**Comment by HaotianXu** [comment]
@stephaneguerrier @coatless I did the proof, here are the tex file and pdf file.
[proof.pdf](https://github.com/SMAC-Group/TTS/files/428527/proof.pdf)
[ACF.zip](https://github.com/SMAC-Group/TTS/files/428529/ACF.zip)

**Comment by stephaneguerrier** [comment]
HI @HaotianXu, thanks a lot for the proof. We included it in the text in Appendix A and I started reviewing it. I think it would be nice to show that

```
T^{\frac{1}{2}}[\tilde{\gamma} \left( h \right) - \hat \gamma \left( h \right)] = o_p(1).
```

This result should be easy to show (I think) but I have not tried. Would you mind to add it?

Merci beaucoup!

**Comment by HaotianXu** [comment]
Hi @stephaneguerrier , I just did it with X_t be linear process (W.N. is a special case), it is not as easy as I expected, and I am not sure it is correct. Could you please have a look?
![img_0971](https://cloud.githubusercontent.com/assets/9465430/17836799/de3252d6-679e-11e6-884c-30f46926149f.JPG)
![img_0972](https://cloud.githubusercontent.com/assets/9465430/17836798/de3055bc-679e-11e6-8cd1-2ca51e938a03.JPG)

**Comment by coatless** [comment]
I'm pretty sure I already proved that part @stephaneguerrier . Sorry @HaotianXu for not catching it sooner.

![screen shot 2016-08-21 at 12 47 21 pm](https://cloud.githubusercontent.com/assets/833642/17838875/7c4a7fd6-679d-11e6-95c0-169afc6accee.png)

![screen shot 2016-08-21 at 12 47 32 pm](https://cloud.githubusercontent.com/assets/833642/17838877/7c500e06-679d-11e6-8e60-1bee093e76ce.png)

![screen shot 2016-08-21 at 12 47 37 pm](https://cloud.githubusercontent.com/assets/833642/17838876/7c4a9232-679d-11e6-9f9f-fd43a3bc5003.png)

**Comment by stephaneguerrier** [comment]
@HaotianXu thanks a lot for sending the proof which is perfectly done. However, (and I might be missing something) why do you assume that Xt is a linear process (i.e X_t = sum \psi W)? In our case, we only need to show this result with Xt = mu + Wt, right? If so, the proof are be simplified. You can also use James’ proof and simplify it but yours is more compact.

**Comment by HaotianXu** [comment]
Hi @stephaneguerrier , this general assumption is proposed by the problem 1.30 on Shumway & Stoffer's book. 
![image](https://cloud.githubusercontent.com/assets/9465430/17839612/90389e9c-67ed-11e6-88e5-4953be124821.png)

I think what I did is the same as James' proof. I'll write down the whole proof soon.

**Comment by stephaneguerrier** [comment]
Ok, sure. Then let's add this as a lemma before the proof the theorem. Then we can use it in the theorem in the white noise case. Does that seem all right to you? Thanks

**Comment by HaotianXu** [comment]
@stephaneguerrier  Yes, I think it's better.

**Comment by HaotianXu** [comment]
Hi@coatless , I cannot edit the appendix, so I attached the tex file below. Could you please add this lemma to the proof of Thm1? Thank you James!
[lemma.zip](https://github.com/SMAC-Group/TTS/files/433333/lemma.zip)

**Comment by stephaneguerrier** [comment]
@HaotianXu Thanks! 

@coatless Can you set up an appointment with Haotian this week to show him how to use github? 

@HaotianXu When you will be able to edit the file, can you complete the appendix for the proof of thm 1? Merci beaucoup!

**Comment by coatless** [comment]
@HaotianXu Let's talk probably on Friday? Ping me on Slack with a time.

@stephaneguerrier Proof was added into the appendix. So, I think this can be closed out?

**Comment by stephaneguerrier** [comment]
@coatless The text was added but still needs to be improved. So let's wait before closing this...
