### ISSUE TITLE
High-frequency example

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/TTS#4]
Gaetan: could you please review, correct and expend a little the example about high-frequency finance in chap 1?

**Comment by stephaneguerrier** [comment]
Hi @moufle7, since github is not correctelt set-up on your computer, just send me by email with the change (if any). Thanks

**Comment by coatless** [comment]
I think this was addressed in: 38f2a46d6a4f835c007a5c81ddb612ae41aa96d9

Thus, this can be closed out?

@stephaneguerrier: To associate commits with an issue use `#number` and you can autoclose the issue with `(close #number)`
