### ISSUE TITLE
Check AIC and Cp

### ISSUE THREAD

**Issue by stephaneguerrier** [SMAC-Group/TTS#7]
Can someone please check the derivations for AIC and Cp? Thanks guys!

**Comment by HaotianXu** [comment]
Hi Stef, I checked the derivations, and found some typos. But I am not sure I can edit the book, so I send you a scanned pdf file. Thank you!
[Cp and AIC.pdf](https://github.com/SMAC-Group/TTS/files/427673/Cp.and.AIC.pdf)

**Comment by stephaneguerrier** [comment]
@HaotianXu Thanks a lot! I have updated this chapter. Could you check again the derivation of the AIC? I did not carefully read it but I think it should now make sense... Let me know. Thanks Haotian!

**Comment by HaotianXu** [comment]
@stephaneguerrier I checked it again, and found only one typo. Immediately after AICc, would "since the unbiased estimator of \log \left( \hat{\sigma}^2 \right)" be "since the unbiased estimator of E[\log \left( \hat{\sigma}^2 \right)]"?

**Comment by stephaneguerrier** [comment]
@HaotianXu Thanks a lot you are right! Does the derivations make sense now?

**Comment by HaotianXu** [comment]
@stephaneguerrier Yes, they make sense!

**Comment by stephaneguerrier** [comment]
Ok, great! Thanks
